name: kassam
description: "Shaxsiy moliyani boshqarish uchun professional dastur."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.2
  bloc: ^8.1.4
  equatable: ^2.0.5
  go_router: ^17.0.0
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  connectivity_plus: ^6.0.3
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.0
  alice: ^1.0.0
  alice_dio: ^1.0.0
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
